---
all:
  children:
    streamin_servers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
      vars:
        # Specific variables for StreaminOS servers
        streamin_user: "{{ ansible_user_id }}"
        streamin_home: "{{ ansible_env.HOME }}"
